#!/usr/bin/env bash
# read contents of file with `while`
# note : only awk is NOT allowed


while read -r line; do 
	USER_1="$(echo -n "$line" | cut -d ':' -f1)"
	PASS_2="$(echo -n "$line" | cut -d ':' -f2)"
	UID_3="$(echo -n "$line" | cut -d ':' -f3)"
	GID_4="$(echo -n "$line" | cut -d ':' -f4)"
	GECOS_5="$(echo -n "$line" | cut -d ':' -f5)"
	HOME_6="$(echo -n "$line" | cut -d ':' -f6)"
	CMD_7="$(echo -n "$line" | cut -d ':' -f7)"

	echo  "The user $USER_1 is part of the $GID_4 gang, lives in $HOME_6 and rides $CMD_7. $UID_3's place is protected by the passcode $PASS_2, more info about the user here: $GECOS_5"

done < /etc/passwd
