#!/usr/bin/env bash
# doubly nested `while` loops
# note : only awk is NOT allowed

h=0;
while [[ $h -lt 13 ]]; do
	echo Hour: $h
	m=1
	while [[ $m -lt 60 ]]; do
		echo $m
		((m++));
	done
	((h++));
done
